language: node_js
node_js:
  - 10
  - 8
  - 6
install:
  - npm i -g npm@5.8.0
  - npm ci
cache:
  directories:
    - node_modules
script:
  - npm run examples:lint
  - npm run examples:test
  - npm run build
  - npm test
  - npm run lint 
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"